name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_LEVEL_UP_CHOICE_BOARD_GAME }}'
          channelId: live
          projectId: level-up-choice-board-game

      - name: Deploy Firestore Rules
        run: |
          echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT_LEVEL_UP_CHOICE_BOARD_GAME }}' > sa.json
          GOOGLE_APPLICATION_CREDENTIALS=sa.json npx firebase-tools deploy --only firestore:rules --project level-up-choice-board-game
          rm -f sa.json

